- name: Checking the rulebook functionality
  hosts: localhost
  sources:
    - name: eda tick
      ansible.eda.tick:
        deploy: 5
  rules:
    - name: Say Hello
      condition: true
      actions:
        run_job_template:
            name: "Hello World"
            organization: "Default"