- name: "Checking the rulebook functionality"
  hosts: localhost
  sources:
    - name: "eda tick"
      ansible.eda.tick:
        deploy: 60
  rules:
    - name: "Say Hello"
      condition: true
      action:
        run_job_template:
            name: "Hello World"
            organization: "Default"