---
- name: Sample Playbook for Hello World
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello World from Ansible Event Driven Automation. Current timestamp: {{ ansible_date_time.date }} {{ ansible_date_time.time }}"