---
- name: Sample Playbook for Hello World
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello World from Ansible Event Driven Automation"
        current_time: "{{ ansible_date_time.iso8601 }}"
        cpu_cores: "{{ ansible_processor_vcpus }}"
        memory_gb: "{{ ansible_memtotal_mb / 1024 }}"
      delegate_to: localhost