---
- name: Sample Playbook for Hello World
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "Hello World from Ansible Event Driven Automation"
        customer_name: "{{ customer_name }}"
        current_time: "{{ ansible_date_time.iso8601 }}"
        server_ip: "{{ ansible_default_ipv4.address }}"
        cpu_cores: "{{ ansible_processor_vcpus }}"
        memory_gb: "{{ ansible_memtotal_mb / 1024 }}"
    - name: Fetch disk space
      ansible.builtin.shell: df -h
      register: disk_space_output

    - name: Fetch system load
      ansible.builtin.shell: uptime
      register: system_load_output

    - name: Fetch network interfaces
      ansible.builtin.shell: ip addr show
      register: network_interfaces_output

    - name: Fetch running processes
      ansible.builtin.shell: ps aux
      register: running_processes_output

    - name: Print all data
      debug:
        var: disk_space_output.stdout_lines
        var: system_load_output.stdout_lines
        var: network_interfaces_output.stdout_lines
        var: running_processes_output.stdout_lines